/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#000000',
        'on-background': '#e7e5e5',
        'primary-fixed': '#d4e3ff',
        'tertiary-fixed': '#ddddfe',
        'on-surface': '#e7e5e5',
        'surface': '#0e0e0e',
        'surface-bright': '#2b2c2c',
        'secondary-container': '#2e3c50',
        'on-tertiary-container': '#4c4e68',
        'on-error': '#490106',
        'tertiary-fixed-dim': '#cecfef',
        'tertiary-container': '#ddddfe',
        'on-tertiary': '#555671',
        'on-primary-fixed-variant': '#005da7',
        'surface-container-highest': '#252626',
        'surface-variant': '#252626',
        'surface-container-low': '#131313',
        'primary-container': '#004883',
        'error-container': '#7f2927',
        'surface-dim': '#0e0e0e',
        'on-primary': '#004178',
        'on-tertiary-fixed': '#3a3c55',
        'secondary-fixed': '#d5e3fd',
        'error': '#ee7d77',
        'error-dim': '#bb5551',
        'on-error-container': '#ff9993',
        'on-secondary-fixed-variant': '#4e5c71',
        'on-surface-variant': '#acabaa',
        'inverse-surface': '#fcf9f8',
        'on-primary-container': '#b5d2ff',
        'secondary-dim': '#909fb6',
        'on-secondary-fixed': '#324054',
        'on-secondary-container': '#b2c0d9',
        'background': '#0e0e0e',
        'inverse-primary': '#0060ad',
        'primary': '#a4c9ff',
        'surface-container-high': '#1f2020',
        'tertiary': '#edecff',
        'inverse-on-surface': '#565555',
        'outline-variant': '#484848',
        'on-secondary': '#122133',
        'secondary-fixed-dim': '#c7d5ee',
        'on-primary-fixed': '#004076',
        'outline': '#767575',
        'primary-fixed-dim': '#bcd6ff',
        'primary-dim': '#8abbff',
        'on-tertiary-fixed-variant': '#565873',
        'secondary': '#909fb6',
        'surface-container': '#191a1a',
        'surface-tint': '#a4c9ff',
        'tertiary-dim': '#cecfef',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
